
modLoader = "javafml"
loaderVersion = "${loader_version_range}" 
license = "${mod_license}"
[[mods]] 
modId = "${mod_id}" 
version = "${mod_version}" 
displayName = "${mod_name}" 
logoFile="assets/visibletraders/icon.png" 
authors = "${mod_authors}"
description = "A mod that allows the player to view locked villager trades"
[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]] 
modId = "neoforge" 
type = "required" 
versionRange = "${neo_version_range}" 
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,1.22)"
ordering = "NONE"
side = "BOTH"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"